# Generated by Django 4.1.7 on 2023-03-24 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=50)),
                ('numero', models.IntegerField(max_length=10)),
                ('bairro', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('cep', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Engenheiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=11)),
                ('crea', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TipoBacia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Bacia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profundidade', models.FloatField(blank=True)),
                ('capacidade', models.FloatField(blank=True)),
                ('largura', models.FloatField(blank=True)),
                ('comprimento', models.FloatField(blank=True)),
                ('engenheiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.engenheiro')),
                ('tipoBacia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tipobacia')),
            ],
        ),
    ]
