# Generated by Django 4.1.3 on 2023-06-23 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='cep',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='engenheiro',
            name='cpf',
            field=models.CharField(max_length=14),
        ),
    ]
